name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build -- --base-href "https://digitalcraftsman.dk"
      - name: Deploy
        run: npx angular-cli-ghpages --dir=dist/digital-craftsman --cname=digitalcraftsman.dk -S --name "Deploy BOT" --email "noemail@mail.com"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}